export const theme = {
  colors: {
    appBackground: '#F9FAFB',
    surfacePrimary: '#FFFFFF',
    surfaceSubtle: '#F9FAFB',
    borderSubtle: '#E5E7EB',
    textHeading: '#101828',
    textStrong: '#0A0A0A',
    textBody: '#4A5565',
    textMuted: '#6A7282',
    textOnDarkMuted: '#DBEAFE',
    linkPrimary: '#155DFC',
    white: '#FFFFFF',
    black: '#000000',
    purple: '#6C5CE7',
    heroGradientStart: '#2B7FFF',
    heroGradientEnd: '#155DFC',
    statBlue: '#2B7FFF',
    statGreen: '#00C950',
    statPurple: '#AD46FF',
    statOrange: '#FF6900',
    quickActionPurpleBg: '#FAF5FF',
    quickActionPurpleText: '#59168B',
    quickActionPurpleIcon: '#9810FA',
    quickActionBlueBg: '#EFF6FF',
    quickActionBlueText: '#1C398E',
    quickActionBlueIcon: '#155DFC',
    quickActionGreenBg: '#F0FDF4',
    quickActionGreenText: '#0D542B',
    quickActionGreenIcon: '#00A63E',
    quickActionOrangeBg: '#FFF7ED',
    quickActionOrangeText: '#CA3500',
    approvalCardBg: '#FFF7ED',
    pendingChipBg: '#FFEDD4',
    pendingChipText: '#CA3500',
    tabActive: '#155DFC',
    tabInactive: '#6A7282',

    // Compatibility aliases for already implemented screens.
    background: '#F9FAFB',
    surface: '#FFFFFF',
    cardSurface: '#F9FAFB',
    border: '#E5E7EB',
    heading: '#101828',
    textPrimary: '#101828',
    textSecondary: '#4A5565',
    link: '#155DFC',
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    xl: 22,
    pill: 999,
  },
  typography: {
    title: {
      fontSize: 24,
      fontWeight: '600',
      color: '#0A0A0A',
      lineHeight: 28,
    },
    sectionTitle: {
      fontSize: 24,
      fontWeight: '600',
      color: '#101828',
      lineHeight: 30,
    },
    statValue: {
      fontSize: 24,
      fontWeight: '800',
      color: '#101828',
      lineHeight: 32,
    },
    itemTitle: {
      fontSize: 20,
      fontWeight: '500',
      color: '#101828',
      lineHeight: 24,
    },
    body: {
      fontSize: 18,
      fontWeight: '500',
      color: '#101828',
      lineHeight: 24,
    },
    caption: {
      fontSize: 18,
      fontWeight: '400',
      color: '#6A7282',
      lineHeight: 20,
    },
    tabLabel: {
      fontSize: 12,
      fontWeight: '500',
      lineHeight: 16,
    },
  },
  iconSize: {
    sm: 14,
    md: 16,
  },
  dimensions: {
    statIconBox: 42,
    tabBarHeight: 74,
  },
  shadow: {
    card: {
      shadowColor: '#000000',
      shadowOpacity: 0.1,
      shadowRadius: 3,
      shadowOffset: { width: 0, height: 1 },
      elevation: 2,
    },
    hero: {
      shadowColor: '#000000',
      shadowOpacity: 0.1,
      shadowRadius: 15,
      shadowOffset: { width: 0, height: 10 },
      elevation: 6,
    },
  },
};
